- name: Setup Nginx
  hosts: frontend

  vars:
    http_port: 80

  tasks:
  - name: Upgrade system
    apt:
      upgrade: dist
      update_cache: yes

  - name: Install Nginx
    apt:
      name: nginx

  - name: Remove default nginx config
    file:
      name: /etc/nginx/sites-enabled/default
      state: absent

  - name: Install system nginx config
    template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

  - name: Install HTTP nginx site
    template:
      src: templates/nginx-http.j2
      dest: /etc/nginx/sites-enabled/http
  
  - name: Reload Nginx to activate HTTP site
    service:
      name: nginx
      state: restarted

- name: Setup Docker
  hosts: backend

  roles:
  - docker
