INSERT INTO "Accounts" VALUES(DEFAULT, 1, 'BTC', 0, '2023-07-01');
INSERT INTO "Accounts" VALUES(DEFAULT, 1, 'BTC', 0, '2023-07-01');

-- TRANSACTIONS

BEGIN;

SELECT * FROM "Accounts" WHERE "Id" = 1;

UPDATE "Accounts" SET "Amount" = 20 WHERE "Id" = 1;

COMMIT;

SELECT * FROM "Accounts" WHERE "Id" = 1;

UPDATE "Accounts" SET "Amount" = 0 WHERE "Id" = 1;

BEGIN;

SELECT * FROM "Accounts" WHERE "Id" = 1;

UPDATE "Accounts" SET "Amount" = 20 WHERE "Id" = 1;

ROLLBACK;

SELECT * FROM "Accounts" WHERE "Id" = 1;

-- LOST UPDATE

--1
BEGIN;

--2
BEGIN;

--1
SELECT * FROM "Accounts" WHERE "Id" = 1;

--2
SELECT * FROM "Accounts" WHERE "Id" = 1;

--1
UPDATE "Accounts" SET "Amount" = 10 WHERE "Id" = 1;

--2
UPDATE "Accounts" SET "Amount" = 20 WHERE "Id" = 1;

--1
COMMIT;

--2
COMMIT;

-- SELECT FOR UPDATE

--1
BEGIN;

--2
BEGIN;

--1
SELECT * FROM "Accounts" WHERE "Id" = 1 FOR UPDATE;

--2
SELECT * FROM "Accounts" WHERE "Id" = 1 FOR UPDATE;

--1
UPDATE "Accounts" SET "Amount" = 10 WHERE "Id" = 1;

--2
UPDATE "Accounts" SET "Amount" = 30 WHERE "Id" = 1;

--1
COMMIT;

--2
COMMIT;

-- VERSIONS

CREATE TABLE "AccountsWithVersion" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "CurrencyCode" text NOT NULL,
    "Amount" numeric NOT NULL,
    "OpenedAt" timestamp with time zone NOT NULL,
    "Version" integer NOT NULL,
    CONSTRAINT "PK_AccountsWithVersion" PRIMARY KEY ("Id")
);

INSERT INTO "AccountsWithVersion" VALUES(DEFAULT, 1, 'BTC', 0, '2023-07-01', 0);
INSERT INTO "AccountsWithVersion" VALUES(DEFAULT, 1, 'BTC', 0, '2023-07-01', 0);

--1
BEGIN;

--2
BEGIN;

--1
SELECT * FROM "AccountsWithVersion" WHERE "Id" = 1;

--2
SELECT * FROM "AccountsWithVersion" WHERE "Id" = 1;

--1
UPDATE "AccountsWithVersion" SET ("Amount", "Version") = (10, 1) WHERE "Id" = 1 AND "Version" = 0;

--2
UPDATE "AccountsWithVersion" SET ("Amount", "Version") = (20, 1) WHERE "Id" = 1 AND "Version" = 0;

--1
COMMIT;

--2
COMMIT;

-- REPEATABLE READ ISOLATION LEVEL

--1
BEGIN;

--2
BEGIN;

--1

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

--2

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

--1
SELECT * FROM "Accounts" WHERE "Id" = 1;

--2
SELECT * FROM "Accounts" WHERE "Id" = 1;

--1
UPDATE "Accounts" SET "Amount" = 10 WHERE "Id" = 1;

--2
UPDATE "Accounts" SET "Amount" = 20 WHERE "Id" = 1;

--1
COMMIT;

--2
COMMIT;