-- PostgreSQL
CREATE TABLE "Withdrawals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "AccountId" integer NOT NULL,
    "CurrencyCode" text NOT NULL,
    "Amount" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ToAddress" text NOT NULL,
    CONSTRAINT "PK_Withdrawals" PRIMARY KEY ("Id")
);

INSERT INTO "Withdrawals" VALUES(DEFAULT, 2, 10, 'BTC', 52, '2023-07-18 12:00:00', 'tb123456');
INSERT INTO "Withdrawals" VALUES(DEFAULT, 2, 10, 'BTC', 14, '2023-07-18 13:00:00', 'tbabcdef');
INSERT INTO "Withdrawals" VALUES(DEFAULT, 2, 10, 'BTC', 20, '2023-07-18 14:00:00', 'tb998877');

-- READ UNCOMMITTED #1

--1
BEGIN;

--2
BEGIN TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

--1
-- PostgreSQL
INSERT INTO "Withdrawals" VALUES(DEFAULT, 2, 10, 'BTC', 52, '2023-07-17', 'tb123456');

--2
SELECT * FROM "Withdrawals";

--1
ROLLBACK;

SELECT * FROM "Withdrawals";

--2
COMMIT;

-- READ COMMITTED #1

--1
BEGIN;

--2
BEGIN TRANSACTION ISOLATION READ COMMITTED;

--1
-- PostgreSQL
INSERT INTO "Withdrawals" VALUES(DEFAULT, 2, 10, 'BTC', 52, '2023-07-17', 'tb123456');

-- MS SQL Server
INSERT INTO "Withdrawals" VALUES(2, 10, 'BTC', 52, DEFAULT, 'tb123456');

--2
SELECT * FROM "Withdrawals";

--1
ROLLBACK;

SELECT * FROM "Withdrawals";

--2
COMMIT;

-- READ COMMITTED #2

--1
BEGIN;

--2
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

--1
SELECT * FROM "Accounts" WHERE "Id" = 1;

--2
SELECT * FROM "Accounts" WHERE "Id" = 1;

--1
UPDATE "Accounts" SET "Amount" = 10 WHERE "Id" = 1;

--2
UPDATE "Accounts" SET "Amount" = 20 WHERE "Id" = 1;

--1
COMMIT;

--2
COMMIT;

-- REPEATABLE READ #1

--1
BEGIN;

--2
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

--1
SELECT * FROM "Accounts" WHERE "Id" = 1;

--2
SELECT * FROM "Accounts" WHERE "Id" = 1;

--1
UPDATE "Accounts" SET "Amount" = 10 WHERE "Id" = 1;

--2
UPDATE "Accounts" SET "Amount" = 20 WHERE "Id" = 1;

--1
COMMIT;

--2
COMMIT;

-- REPEATABLE READ #2

--1
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

--2
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;

--1
SELECT SUM("Amount") FROM "Withdrawals" WHERE "CreatedAt" >= '2023-07-18' AND "CreatedAt" < '2023-07-19';

--2
SELECT SUM("Amount") FROM "Withdrawals" WHERE "CreatedAt" >= '2023-07-18' AND "CreatedAt" < '2023-07-19';

--1
INSERT INTO "Withdrawals" VALUES(DEFAULT, 2, 10, 'BTC', 10, '2023-07-18 15:00:00', 'tb554433');

--2
INSERT INTO "Withdrawals" VALUES(DEFAULT, 2, 10, 'BTC', 10, '2023-07-18 15:00:00', 'tb334455');

--1
COMMIT;

--2
COMMIT;


DELETE FROM "Withdrawals" WHERE "ToAddress" IN ('tb334455', 'tb554433');

-- SERIALIZABLE #2

--1
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

--2
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;

--1
SELECT SUM("Amount") FROM "Withdrawals" WHERE "CreatedAt" >= '2023-07-18' AND "CreatedAt" < '2023-07-19';

--2
SELECT SUM("Amount") FROM "Withdrawals" WHERE "CreatedAt" >= '2023-07-18' AND "CreatedAt" < '2023-07-19';

--1
INSERT INTO "Withdrawals" VALUES(DEFAULT, 2, 10, 'BTC', 10, '2023-07-18 15:00:00', 'tb554433');

--2
INSERT INTO "Withdrawals" VALUES(DEFAULT, 2, 10, 'BTC', 10, '2023-07-18 15:00:00', 'tb334455');

--1
COMMIT;

--2
COMMIT;
