version: "3.8"

name: "open-telemetry-lab"

services:
  api-gateway: 
    build:
      context: ./src
      dockerfile: ApiGateway/Dockerfile
    environment:
      - Clients__BankingService=http://banking-service:80
      - ASPNETCORE_URLS=http://+:80
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - 9000:80

  banking-service: 
    build:
      context: ./src
      dockerfile: BankingService/Dockerfile
    environment:
      - Clients__BlockchainService=http://blockchain-service:80
      - Kestrel__Endpoints__Http__Url=http://+:81
      - Kestrel__Endpoints__Http__Protocols=Http1
      - Kestrel__Endpoints__gRPC__Url=http://+:80
      - Kestrel__Endpoints__gRPC__Protocols=Http2
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317

  blockchain-service: 
    build:
      context: ./src
      dockerfile: BlockchainService/Dockerfile
    environment:
      - Kestrel__Endpoints__Http__Url=http://+:81
      - Kestrel__Endpoints__Http__Protocols=Http1
      - Kestrel__Endpoints__gRPC__Url=http://+:80
      - Kestrel__Endpoints__gRPC__Protocols=Http2
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317

  jaeger:
    image: jaegertracing/all-in-one:1.51.0
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - 3000:3000
    volumes:
    - ./configs/grafana-datasources:/etc/grafana/provisioning/datasources

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - 9200:9200
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
