// <auto-generated />
using LoanService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoanService.Migrations
{
    [DbContext(typeof(LoanServiceDbContext))]
    [Migration("20231226141344_AddLoanOffering")]
    partial class AddLoanOffering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoanService.Domain.LoanOffering", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Months")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("LoanOfferings");

                    b.HasData(
                        new
                        {
                            Name = "Best Loan",
                            InterestRate = 0.05m,
                            MaxAmount = 10000m,
                            Months = 12
                        },
                        new
                        {
                            Name = "Worst Loan",
                            InterestRate = 0.25m,
                            MaxAmount = 50000m,
                            Months = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
