version: "3.8"

name: "tcp-ip-lab"

services:

  server:
    build:
      context: ./src/Server
      dockerfile: Dockerfile

  client:
    build:
      context: ./src/Client
      dockerfile: Dockerfile
    depends_on:
      - server
