name: "web-api"

volumes:
  db:
    name: db

services:
  # Build WebApi image and run container
  web_api:
    build:
      context: ../src
      dockerfile: ../src/WebApi/Dockerfile
    environment:
      ConnectionStrings__DockerCompose: Host=db;Database=DockerCompose;Username=db_creator;Password=12345678;Maximum Pool Size=50;Connection Idle Lifetime=60;
    ports:
      - "8000:80"

  # Run PostgreSQL from image
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=db_creator
      - POSTGRES_PASSWORD=12345678
    volumes:
      - db:/var/lib/postgresql/data
