version: "3.8"

name: "udp-lab"

services:
  udp-server: 
    build:
      context: ./src
      dockerfile: UdpServer/Dockerfile

  udp-client: 
    build:
      context: ./src
      dockerfile: UdpClient/Dockerfile
    environment:
      - HOST=udp-server
    depends_on:
      - udp-server
